### ISSUE TITLE
XSCALE.LP file not created

### ISSUE THREAD

**Issue by lucajovine** [gsantoni/ccCluster#11]
Just installed ccCluster on a new machine, and am getting:

> ccCalc -f 4-1-05_XDS_ASCII.HKL 4-1-13_XDS_ASCII.HKL 4-1-15_XDS_ASCII.HKL
	Calculating CC between specified files
	File 4-1-05_XDS_ASCII.HKL has been loaded
	File 4-1-13_XDS_ASCII.HKL has been loaded
	File 4-1-15_XDS_ASCII.HKL has been loaded
	Calculated correlation between 4-1-05_XDS_ASCII.HKL and 4-1-13_XDS_ASCII.HKL
	Calculated correlation between 4-1-05_XDS_ASCII.HKL and 4-1-15_XDS_ASCII.HKL
	Calculated correlation between 4-1-13_XDS_ASCII.HKL and 4-1-15_XDS_ASCII.HKL
	262.647 111.380 68.526
	262.708 111.597 68.655
	263.260 110.957 68.229
> ccCluster-gui -i ccClusterLog.txt
	ccCluster - HCA for protein crystallography
	G. Santoni and A. Popov, 2015
	              v .   ._, |_  .,
	           `-._\/  .  \ /    |/_
	               \  _\, y | \//
	         _\_.___\, \/ -.\||
	           `7-,--.`._||  / / ,
	           /'     `-. `./ / |/_.'
	                     |    |//
	                     |_    /
	                     |-   |
	                     |   =|
	                     |    |
	--------------------/ ,  . \--------._
	
	Traceback (most recent call last):
	  File "/usr/local/conda/miniconda3/envs/cccluster/lib/python3.10/site-packages/ccCluster/ccCluster_gui.py", line 228, in setupUi
	    self.tabWidget.addTab(resultsTab(float(L[1]), L[2].strip(), L[3].strip(), L[4]),L[1]+L[2]+L[3].strip())
	  File "/usr/local/conda/miniconda3/envs/cccluster/lib/python3.10/site-packages/ccCluster/resultsTab.py", line 68, in __init__
	    with open(self.CurrentDir+'/cc_Cluster_%.2f_%s_%s/XSCALE.LP'%(float(thr), cls, anom), 'r') as LogFile:
	FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/cccluster/test/cc_Cluster_0.45_1_ano/XSCALE.LP'
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "/usr/local/conda/miniconda3/envs/cccluster/bin/ccCluster-gui", line 8, in <module>
	    sys.exit(main())
	  File "/usr/local/conda/miniconda3/envs/cccluster/lib/python3.10/site-packages/ccCluster/ccCluster_gui.py", line 377, in main
	    ex = MainWindow()
	  File "/usr/local/conda/miniconda3/envs/cccluster/lib/python3.10/site-packages/ccCluster/ccCluster_gui.py", line 355, in __init__
	    self.setupUi(self)
	  File "/usr/local/conda/miniconda3/envs/cccluster/lib/python3.10/site-packages/ccCluster/ccCluster_gui.py", line 232, in setupUi
	    self.tabWidget.addTab(resultsTab(float(L[1]), L[2].strip(), L[3].strip(), 'unk'),L[1]+L[2]+L[3].strip())
	  File "/usr/local/conda/miniconda3/envs/cccluster/lib/python3.10/site-packages/ccCluster/resultsTab.py", line 68, in __init__
	    with open(self.CurrentDir+'/cc_Cluster_%.2f_%s_%s/XSCALE.LP'%(float(thr), cls, anom), 'r') as LogFile:
	FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/cccluster/test/cc_Cluster_0.45_1_ano/XSCALE.LP'

**Comment by lucajovine** [comment]
OK, this was due to a .cc_cluster.log file from a previous run, that I copied over without realizing. Since it obviously can conflictr, maybe program should check for this and delete it before a new run?
